= consul
Jon Brohauge <jonbrohauge@gmail.com>
:linkattrs:

== TL;DR

https://www.consul.io/[consul, window="_blank"] is a key/value store.
In this project it does not matter if it is specifically consul being used.
I just needed a key/value store that understands JSON.
If you wish to use another key/value store, please do not hesitate to submit a PR.

== Initial Setup

Setup you installation by following the instructions from https://www.consul.io/[consul, window="_blank"].
During development I have used a locally run docker container.
__*TODO: Add how to run consul locally via docker*__

== Communication

The URL where the configuration is placed is: `[BASE_CONSUL_URL]/pijenmon/instance/[hostname]`,
 i.e. `http://dev.local:[PORT]/pijenmon/instance/raspberrypizerow` for an instance called `RaspberryPiZeroW` communicating with my development environment, called `dev.local`.

== Format

The format of the JSON response from consul is important. Minimum requirements are the following key/value-pairs:
[source,json]
----
{
"hostname": "RaspberryPiZeroW",
"jenkins_url": "http://localhost:8080/",
"organizations": ["Organization1", "Organization2", "Organization3"]
}
----

The `hostname` is the name of the Raspberry Pi unit you wish to use.
The `jenkins_url` is the url to the Jenkins instance running the jobs, that are to be monitored for build status.
The `organizations` is a list of GitHub Organizations that contain the jobs, that are to be monitored for build status.
